# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 07:49
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Author = apps.get_model('non_nullable_field', 'Author')
    Author.objects.create(name='Author 1')
    Author.objects.create(name='Author 2')


def backwards(apps, schema_editor):
    Author = apps.get_model('non_nullable_field', 'Author')
    Author.objects.filter(name='Author 1').delete()
    Author.objects.filter(name='Author 2').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('non_nullable_field', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
