# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_nullable_field', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='homepage',
            field=models.URLField(null=True),
        ),
    ]
