# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_nullable_field', '0004_populate_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='homepage',
            field=models.URLField(),
        ),
    ]
