# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app_name', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='rename_app_author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='rename_app_book',
        ),
    ]
