# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app_name', '0003_pin_db_tables'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
