# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alter_pk', '0004_populate_post_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
