# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alter_pk', '0007_post_change_author_name_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_name',
            new_name='author',
        ),
    ]
